site_name: 我的第一个站点
site_description: # (站点注释)
site_author: # (站点作者名称)
site_url: # (站点地址)
 
copyright: # (版权声明相关文本)
 
# nav 区域指定站点上能看到的页面。
# 下面的配置代码仅作示范。注意配置的页面对应的 MarkDown 源码文件必须存在。
nav:
  - 主页: ./docs/index.md
  - 章节列表：./docs/test.md
  - 关于我: ./docs/about.md