name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - main # 监测的分支
jobs:
  deploy:
    runs-on: ubuntu-latest # 拉去虚拟环境镜像
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install MkDocs
        run: pip install -r requirements.txt # 虚拟环境安装依赖

      - name: Build and deploy
        env: GITHUB_TOKEN: ${{secrets.GITHUB_TIKEN}}
        run: mkdocs gh-deploy --force # 会在虚拟环境部署站点，无需本地使用此命令